language: python
sudo: required
dist: xenial
python: '3.7'
env:
    - PIPENV_IGNORE_VIRTUALENVS=1
cache:
  - pip

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv check ./app ./tests
  - pipenv run pytest ./tests

branches:
  only:
    - master
