name: Master

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t onsdigital/eq-translations:latest .
      - name: Push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [latest]"
          docker push onsdigital/eq-translations:latest